# Generated by Django 6.0.6 on 2026-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_delivery_cost_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
