# Generated by Django 3.2.25 on 2026-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
